-- =============================================================
-- 0013. 댓글 시스템 (Phase B)
--
-- - comments 테이블: qa_id 참조, 1단계 답글만 (parent_id의 parent_id는 null이어야)
-- - status: visible / hidden / deleted
-- - RLS:
--     visible은 anon/모두 조회
--     hidden은 본인 / admin / 해당 글 doctor만 조회
--     작성: 로그인 사용자 (author_id = auth.uid())
--     수정 (body): 본인만
--     가림/복원/삭제: admin / 해당 글 doctor / (삭제는 본인도)
-- =============================================================

-- 1. enum
do $$
begin
  if not exists (select 1 from pg_type where typname = 'comment_status') then
    create type public.comment_status as enum ('visible', 'hidden', 'deleted');
  end if;
end$$;

-- 2. 테이블
create table if not exists public.comments (
  id          bigint generated by default as identity primary key,
  qa_id       bigint not null references public.qas(id) on delete cascade,
  author_id   uuid references auth.users(id) on delete set null,
  parent_id   bigint references public.comments(id) on delete cascade,
  body        text not null check (char_length(body) between 1 and 2000),
  status      public.comment_status not null default 'visible',
  like_count  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- 3. 답글의 답글 방지 트리거
create or replace function public.check_comment_depth()
returns trigger
language plpgsql
as $func$
begin
  if new.parent_id is not null then
    if exists (
      select 1 from public.comments
      where id = new.parent_id and parent_id is not null
    ) then
      raise exception '답글의 답글은 허용되지 않습니다 (1단계 답글만 가능)';
    end if;
  end if;
  return new;
end;
$func$;

drop trigger if exists comments_depth_check on public.comments;
create trigger comments_depth_check
  before insert or update on public.comments
  for each row execute function public.check_comment_depth();

-- 4. 인덱스
create index if not exists comments_qa_idx on public.comments(qa_id, created_at desc);
create index if not exists comments_parent_idx on public.comments(parent_id);
create index if not exists comments_author_idx on public.comments(author_id);

-- 5. updated_at 자동 갱신 (set_updated_at 함수는 0010에서 정의됨)
drop trigger if exists comments_updated_at on public.comments;
create trigger comments_updated_at
  before update on public.comments
  for each row execute function public.set_updated_at();

-- 6. RLS
alter table public.comments enable row level security;

-- ── select: visible은 모두, hidden은 작성자 본인 / admin / 해당 글 doctor에게만
drop policy if exists "comments_select" on public.comments;
create policy "comments_select" on public.comments
  for select using (
    status = 'visible'
    or public.is_admin()
    or (auth.uid() is not null and auth.uid() = author_id)
    or (
      -- 해당 qa의 doctor_id가 현재 사용자의 doctor_id와 일치하는 경우만
      -- (current_doctor_id()가 null일 때 doctor_id null인 글까지 잡지 않도록 IS NOT NULL 체크)
      public.current_doctor_id() is not null
      and exists (
        select 1 from public.qas q
        where q.id = qa_id
          and q.doctor_id = public.current_doctor_id()
      )
    )
  );

-- ── insert: 로그인 사용자, author_id = auth.uid()
drop policy if exists "comments_insert" on public.comments;
create policy "comments_insert" on public.comments
  for insert with check (
    auth.uid() is not null
    and author_id = auth.uid()
  );

-- ── 본인 댓글 수정 (body 변경용)
drop policy if exists "comments_update_self" on public.comments;
create policy "comments_update_self" on public.comments
  for update using (
    auth.uid() is not null and auth.uid() = author_id
  ) with check (
    auth.uid() is not null and auth.uid() = author_id
  );

-- ── 본인 댓글 삭제 (DELETE)
drop policy if exists "comments_delete_self" on public.comments;
create policy "comments_delete_self" on public.comments
  for delete using (
    auth.uid() is not null and auth.uid() = author_id
  );

-- ── admin / 해당 원장: 모든 권한 (가림 status='hidden' / 복원 / 삭제 / 강제 select 등)
drop policy if exists "comments_admin_all" on public.comments;
create policy "comments_admin_all" on public.comments
  for all using (
    public.is_admin()
    or (
      public.current_doctor_id() is not null
      and exists (
        select 1 from public.qas q
        where q.id = qa_id and q.doctor_id = public.current_doctor_id()
      )
    )
  ) with check (
    public.is_admin()
    or (
      public.current_doctor_id() is not null
      and exists (
        select 1 from public.qas q
        where q.id = qa_id and q.doctor_id = public.current_doctor_id()
      )
    )
  );

-- 7. grant
grant select, insert, update, delete on public.comments to authenticated;
grant select on public.comments to anon;
grant usage, select on sequence public.comments_id_seq to authenticated;
